### ISSUE TITLE
Looking for new maintainer(s) & owner(s)

### ISSUE THREAD

**Issue by colinkiama** [AestheticalZ/tooter#1]
I am no longer interested in continuing the project but the idea is pretty cool. So I think it should continue to be developed.

Reply if you're interested in owning the project.

**Comment by AestheticalZ** [comment]
I am interested.

**Comment by colinkiama** [comment]
> I am interested.

Great! Well I'm not working on this project anymore so do you want me to hand this project over to you?

**Comment by AestheticalZ** [comment]
Sure!

**Comment by colinkiama** [comment]
I've sent a transfer request. You just need to accept it then this is all yours!
